### PR TITLE
feat(style): allow one statement inline blocks

### PR DESCRIPTION
**Pull request by voxpelli**
This makes the code more readable in cases and thus one should be allowed to do it.

Ping @hugowetterberg @ptte @simme

### CODE REVIEW

**Comment by simme** [comment]
+1

**Comment by ptte** [comment]
would one example be 

```
if (true) return;
```
?

**Comment by voxpelli** [comment]
nope, it would be: `if (true) { return; }`

**Comment by ptte** [comment]
Okay!

**Pull request merged**
